#!/bin/bash

output_csv="ebs_details.csv"
echo "Profile Name,EBS Tag: Name,EBS Tag: kubernetes.io/created-for/pvc/name,Volume ID,Size,Created" > $output_csv

# Check if 'paas' command is available
if ! command -v paas > /dev/null; then
    echo "The 'paas' command is not available."
    exit 1
fi

# Get customer data from 'paas inventory'
paas_output=$(paas inventory | tail -n +2) # ignore header

# Parse the paas output
echo "$paas_output" | while IFS=, read -r cloud account customer awsRole azureSubscription region environment cluster version kubernetesModuleVersion helmModuleVersion kustomizeGen2ModuleVersion one20HelmModuleVersion kustomizeBaseVersion mdmVersion rdmVersion dqitVersion isHelm kustomizeVersion ONEVersion MMMEnabled MDMEnabled RDMEnabled DQITEnabled DSEnabled mantaEnabled isBackbone K8sVersion DBVersion DBSize isOrlop; do
    if [ "$cloud" == "aws" ]; then
        # 'customer' is directly extracted from the 'paas' output
        profile_name="$customer" # Using customer name as profile name

        # AWS CLI command to fetch all EBS volumes
        volumes=$(aws ec2 describe-volumes \
                  --region "$region" \
                  --query "Volumes[].[VolumeId, Size, CreateTime, State, Tags[?Key=='Name'].Value | [0], Tags[?Key=='kubernetes.io/created-for/pvc/name'].Value | [0]]" \
                  --output text --profile "$profile_name")

        # Process each volume
        echo "$volumes" | while read -r volume_id size create_time state tag_name pvc_name; do
            if [ "$state" == "available" ]; then  # Only process available volumes
                echo "Profile: $profile_name, Region: $region, Volume ID: $volume_id"
                echo "$profile_name,$tag_name,$pvc_name,$volume_id,$size,$create_time" >> $output_csv
            fi
        done
    fi
done

echo "CSV file created: $output_csv"

