name: AWS EBS Manager CI

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: GitHub Actions linter
      uses: docker://rhysd/actionlint:1.6.27

    - name: Lint GitHub Actions workflow YAML
      uses: ibiqlik/action-yamllint@v3.1

    - name: Ensure aws-ebs-manager.sh is executable
      run: |
        test -x aws-ebs-manager.sh || (echo "Script is not executable"; exit 1)

    - name: Run ShellCheck (linter)
      uses: ludeeus/action-shellcheck@master

    - name: Run shfmt (formatter check)
      run: |
        go install mvdan.cc/sh/v3/cmd/shfmt@latest
        "$HOME/go/bin/shfmt" -d aws-ebs-manager.sh

    - name: Run Bats (basic test cases)
      run: |
        sudo apt-get update
        sudo apt-get install -y bats
        if compgen -G "tests/*.bats" > /dev/null; then
          bats tests/
        else
          echo "No tests found, skipping bats."
        fi

    - name: Run bashate (style checker)
      run: |
        pip install bashate
        bashate aws-ebs-manager.sh

    - name: Run Trivy vulnerability scanner (scripts)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: .
        skip-dirs: tests,.github

